{
 "title": "Kafka Service",
 "description": "Kafka Service",
 "tags": [
  "murron-downstream",
  "logstash-upstream",
  "cruise-control-downstream",
  "secor-upstream",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"kafka\"}, cluster)"
    }
   },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\".+\", topic!~\".*Cruise.*\", topic!=\"slogs\"}, topic)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"kafka\", cluster=\"$cluster\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum by(instance)(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\"}))",
     "legendFormat": "count",
     "target": "count(sum by(instance)(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\"}))"
    },
    {
     "expr": "count(up{cluster=\"$cluster\", job=\"kafka-cluster\", az_id!=\"\"})",
     "legendFormat": "expected"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{cluster=\"$cluster\"} > 0",
     "legendFormat": "Cluster Controller: {{instance}}"
    }
   ]
  },
  {
   "title": "Total partition count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum by (partition, topic) (kafka_cluster_partition_replicascount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}))",
     "legendFormat": "partition count"
    },
    {
     "expr": "sum(kafka_cluster_partition_underreplicated{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "under_replicated"
    },
    {
     "expr": "sum(kafka_cluster_partition_insyncreplicascount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"} < 1)",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Replica Count Per Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_replicascount{cluster=\"$cluster\",topic=~\"$[[Topic]]|$Topic\", instance=~\"$[[instance]]|$instance\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_cluster_partition_underreplicated{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}) > 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_cluster_partition_underreplicated{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Offline partitions count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount{cluster=\"$cluster\"})",
     "legendFormat": "offline_partition_count"
    }
   ]
  },
  {
   "title": "Unclean leader elections per sec",
   "type": "graph",
   "description": "Number of unclean leader elections per second.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_controller_controllerstats_uncleanleaderelectionspersec{cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Total (per sec)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"$cluster\", topic=~\"$[[Topic]]|$Topic\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_messagesin_total{cluster=\"$cluster\", topic=~\"$Topic\", instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate by Topic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic)(irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\"$[[Topic]]|$Topic\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate by Topic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", topic=~\"$[[Topic]]|$Topic\", instance=~\"$[[instance]]|$instance\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemFree{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(node_disk_bytes_read{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))\n",
     "legendFormat": "reads"
    },
    {
     "expr": "avg(irate(node_disk_bytes_written{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(node_filesystem_free{asg=\"$cluster-kafka\", mountpoint=\"/mnt\", instance=~\"$[[instance]]|$instance\"}) / avg(node_filesystem_size{asg=\"$cluster-kafka\", mountpoint=\"/mnt\", instance=~\"$[[instance]]|$instance\"}) * 100",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Maximum Replication Lag",
   "type": "graph",
   "description": "Maximum lag in messages between the follower and leader replicas.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_maxlag{cluster=\"$cluster\",instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{asg=\"$cluster-kafka\",mode=\"idle\",instance=~\"$[[instance]]|$instance\"}[1m])) * 100",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Replica imbalance count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_preferredreplicaimbalancecount{cluster=\"$cluster\"})",
     "legendFormat": "replica_imbalance_count"
    }
   ]
  },
  {
   "title": "Packet tx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets{asg=\"$cluster-kafka\", instance=~\"$instance\", device=\"tun1\"}[1m])",
     "legendFormat": "{{instance}}-tx"
    }
   ]
  },
  {
   "title": "Packet rx",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets{asg=\"$cluster-kafka\", instance=~\"$instance\", device=\"tun1\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk block write errors (Usually bad brokers)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "host.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host:\"{{$cluster}}\" AND host:\"kafka\" AND \"I/O error\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top & bottom 3 partition count /broker",
   "type": "graph",
   "description": "Top and bottom 3 brokers should have same number of partitions.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(3, kafka_server_replicamanager_partitioncount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "topk(3, kafka_server_replicamanager_partitioncount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top & bottom 3 Leader/Broker",
   "type": "graph",
   "description": "Top and bottom brokers leader counts per broker. ",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, kafka_server_replicamanager_leadercount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "bottomk(3, kafka_server_replicamanager_leadercount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_controller_controllerstats_isrchangerateandtimems{cluster=\"$cluster\"}[1m])",
     "legendFormat": "ISR Change Rate - {{instance}}"
    },
    {
     "expr": "irate(kafka_controller_controllerstats_autoleaderbalancerateandtimems{cluster=\"$cluster\"}[1m])",
     "legendFormat": "AutoLeaderBalancer Rate - {{instance}}"
    },
    {
     "expr": "irate(kafka_controller_controllerstats_leaderelectionrateandtimems{cluster=\"$cluster\"}[1m])",
     "legendFormat": "Leader Election Rate - {{instance}}"
    },
    {
     "expr": "irate(kafka_controller_controllerstats_partitionreassignmentrateandtimems{cluster=\"$cluster\"}[1m])",
     "legendFormat": "Parittion Reassignment  Rate - {{instance}}"
    }
   ]
  },
  { "title": "Brokers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(instance)(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Leader Count per Broker",
   "type": "graph",
   "description": "Number of leaders on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Count per Broker",
   "type": "graph",
   "description": "Number of partitions on this broker. This should be mostly even across all brokers.",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_partitioncount{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In by Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In by Brokers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out by Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out by Brokers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", topic=~\"$Topic\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Replication Bytes In",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_replicationbytesin_total{cluster=\"$cluster\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "rx"
    }
   ]
  },
  {
   "title": "Replication Bytes In by Brokers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(kafka_server_brokertopicmetrics_replicationbytesin_total{cluster=\"$cluster\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Replication Bytes Out",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_replicationbytesout_total{cluster=\"$cluster\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Replication Bytes Out by Brokers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(irate(kafka_server_brokertopicmetrics_replicationbytesout_total{cluster=\"$cluster\",instance=~\"$[[instance]]|$instance\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log flush stats(max)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(kafka_log_logflushstats_logflushrateandtimems_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log flush stats(avg)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kafka_log_logflushstats_logflushrateandtimems_count{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "log flush stats(per broker)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_log_logflushstats_logflushrateandtimems_count{cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Request Queue Size",
   "type": "graph",
   "description": "Size of the request queue. A congested request queue will not be able to process incoming or outgoing requests",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestchannel_requestqueuesize{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "he average fraction of time the request handler threads are idle. Should always be above 30%.",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]) / 10000000)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle By Instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 63 },
   "targets": [
    {
     "expr": "avg(irate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]) / 10000000) by (instance)"
    }
   ]
  },
  {
   "title": "Failed Fetch Requests Rate",
   "type": "graph",
   "description": "Fetch request rate for requests that failed.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{cluster=\"$cluster\", topic=~\".+\", topic!~\"__.*\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{cluster=\"$cluster\", request=~\".*Fetch.*\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Request Fetch Total Time",
   "type": "graph",
   "description": "Request fetch total time",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(irate(kafka_network_requestmetrics_totaltimems{cluster=\"$cluster\", request=~\".*Fetch.*\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Total Producer Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_totalproducerequests_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Failed Producer Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 75 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Coordinator Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 75 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{cluster=\"$cluster\", request=~\".*Coordinator.*\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "BytesPerFetchRequest",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", topic=~\"$Topic\", instance=~\"$instance\"}[1m])/irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{cluster=\"$cluster\", topic=~\"$Topic\", instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "BytesPerProduceRequest",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 81 },
   "targets": [
    {
     "expr": "avg(irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", topic=~\"$Topic\", instance=~\"$instance\"}[1m])/irate(kafka_server_brokertopicmetrics_totalproducerequests_total{cluster=\"$cluster\", topic=~\"$Topic\", instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Offset Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 81 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_network_requestmetrics_requests_total{cluster=\"$cluster\", request=~\".*Offset.*\", instance=~\"$[[instance]]|$instance\"}[1m])) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  { "title": "Purgatory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Expired Delayed Produce (Offsets Commits)",
   "type": "timeseries",
   "description": "Expired Delayed Produce in Purgatory, applies to the topics needs to be produced with acks=-1 (e.g. __consumer_offsets) topic",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "irate(kafka_server_delayedproducemetrics_expires_total{cluster=\"$cluster\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Purgatory Fetch Sizes (top 5)",
   "type": "graph",
   "description": "The request purgatory serves as a temporary holding pen for produce and fetch requests waiting to be satisfied. Keeping an eye on the size of purgatory is useful to determine the underlying causes of latency. Increases in consumer fetch times, for example, can be easily explained if there is a corresponding increase in the number of fetch requests in purgatory.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{cluster=\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Purgatory Fetch Sizes",
   "type": "graph",
   "description": "The request purgatory serves as a temporary holding pen for produce and fetch requests waiting to be satisfied. Keeping an eye on the size of purgatory is useful to determine the underlying causes of latency. Increases in consumer fetch times, for example, can be easily explained if there is a corresponding increase in the number of fetch requests in purgatory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{cluster=\"$cluster\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{cluster=\"$cluster\"})",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Purgatory Heartbeat Sizes (top 5)",
   "type": "graph",
   "description": "The request purgatory serves as a temporary holding pen for produce and fetch requests waiting to be satisfied. Keeping an eye on the size of purgatory is useful to determine the underlying causes of latency. Increases in consumer fetch times, for example, can be easily explained if there is a corresponding increase in the number of fetch requests in purgatory.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_heartbeat{cluster=\"$cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Purgatory Heartbeat Sizes",
   "type": "graph",
   "description": "The request purgatory serves as a temporary holding pen for produce and fetch requests waiting to be satisfied. Keeping an eye on the size of purgatory is useful to determine the underlying causes of latency. Increases in consumer fetch times, for example, can be easily explained if there is a corresponding increase in the number of fetch requests in purgatory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_heartbeat{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_heartbeat{cluster=\"$cluster\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_heartbeat{cluster=\"$cluster\"})",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "CPU Idle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{asg=\"$cluster-kafka\",mode=\"idle\",instance=~\"$[[instance]]|$instance\"}[1m]) * 100) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 110 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 110 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free{asg=\"$cluster-kafka\", mountpoint=\"/mnt\", instance=~\"$[[instance]]|$instance\"}/node_filesystem_size{asg=\"$cluster-kafka\", mountpoint=\"/mnt\", instance=~\"$[[instance]]|$instance\"})*100",
     "legendFormat": "free-{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptor Allocations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{asg=\"$cluster-kafka\",instance=~\"$[[instance]]|$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 116 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[5m])) by(mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk write errors (/mnt)",
   "type": "graph",
   "description": "Any disk write errors are shown here.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 116 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_device_error{asg=\"$cluster-kafka\", mountpoint=\"/mnt\"} > 0"
    }
   ]
  },
  {
   "title": "ASG Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "dimensions": { "AutoScalingGroupName": "$cluster-kafka" },
     "metricName": "GroupTotalInstances",
     "namespace": "AWS/AutoScaling",
     "region": "us-east-1",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(namedprocess_namegroup_cpu_user_seconds_total{asg=\"$cluster-kafka\",instance=~\"$[[instance]]|$instance\"}[1m])) by (groupname)",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{asg=\"$cluster-kafka\"})",
     "legendFormat": "1min"
    },
    {
     "expr": "avg(node_load5{asg=\"$cluster-kafka\"})",
     "legendFormat": "5min"
    },
    {
     "expr": "avg(node_load15{asg=\"$cluster-kafka\"})",
     "legendFormat": "15min"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Incoming Kafka Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_replicationbytesin_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "replication"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesin_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "topic"
    }
   ]
  },
  {
   "title": "Outgoing Kafka Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_replicationbytesout_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "replication"
    },
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_bytesout_total{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "topic"
    }
   ]
  },
  {
   "title": "System Bytes rx/tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "rx"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Average Packet rx/tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_network_receive_packets{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "rx"
    },
    {
     "expr": "avg(irate(node_network_transmit_packets{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Top 10 Packet rx/tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "topk(10, irate(node_network_receive_packets{asg=\"$cluster-kafka\"}[1m]))",
     "legendFormat": "{{instance}}-rx"
    },
    {
     "expr": "topk(10, irate(node_network_transmit_packets{asg=\"$cluster-kafka\"}[1m]))",
     "legendFormat": "{{instance}}-tx"
    }
   ]
  },
  {
   "title": "Network Idleness",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle. Should always be above 30%.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_socketserver_networkprocessoravgidlepercent{cluster=\"$cluster\", instance=~\"$[[instance]]|$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Udp_RcvbufErrors",
   "type": "graph",
   "description": "Indicates hitting max nebula throughput.\n\nIncremented when sock_queue_rcv_skb reports that no memory is available; this happens if sk->sk_rmem_alloc is greater than or equal to sk->sk_rcvbuf.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (rate(node_netstat_Udp_RcvbufErrors{instance=~\"$cluster-kafka-.+\"}[1m]))",
     "legendFormat": "max"
    },
    {
     "expr": "avg(rate(node_netstat_Udp_RcvbufErrors{instance=~\"$cluster-kafka-.+\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "min(rate(node_netstat_Udp_RcvbufErrors{instance=~\"$cluster-kafka-.+\"}[1m]))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 143 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_netstat_Tcp_RetransSegs{asg=\"$cluster-kafka\", instance=~\"$[[instance]]|$instance\"}[1m]))",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Kernel TCP OOM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 143 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host:\"$cluster-kafka\" AND type:\"kernel\" AND \"TCP: out of memory -- consider tuning tcp_mem\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Memory used (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\", area=\"heap\", job=\"kafka-cluster\"}",
     "legendFormat": "{{area}} memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Memory used (Non Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{cluster=\"$cluster\", area=\"nonheap\", job=\"kafka-cluster\"}",
     "legendFormat": "{{area}} memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "Young  Gen - GC count [G1]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{cluster=~\"$cluster\", gc=\"G1 Young Generation\", job=\"kafka-cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Old  Gen - GC count [G1]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{cluster=\"$cluster\", gc=\"G1 Old Generation\", job=\"kafka-cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Young Gen - GC time / 1 min. rate [G1]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{cluster=\"$cluster\", gc=\"G1 Young Generation\", job=\"kafka-cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Old Gen - GC time / 1 min. rate [G1]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{cluster=\"$cluster\", gc=\"G1 Old Generation\", job=\"kafka-cluster\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Topic partitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 179 },
   "repeat": "Topic",
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Partitions",
     "type": "stat",
     "description": "Number of partitions for this topic",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by(partition)(kafka_cluster_partition_replicascount{cluster=\"$cluster\", topic=\"$Topic\", instance=~\"$[[instance]]|$instance\"}))"
      }
     ]
    },
    {
     "title": "Replica Count",
     "type": "table-old",
     "description": "Number of replicas per partition. 2 replicas per partition is the sweet spot.",
     "gridPos": { "h": 9, "w": 10, "x": 4, "y": 138 },
     "targets": [
      {
       "expr": "sum by(partition, topic)(kafka_cluster_partition_replicascount{cluster=\"$cluster\", topic=\"$Topic\", instance=~\"$[[instance]]|$instance\"})"
      }
     ]
    },
    {
     "title": "In Sync Replica Count",
     "type": "table-old",
     "description": "Number of in sync replicas. Less than 2 in sync replicas is a problem.",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 138 },
     "targets": [
      {
       "expr": "sum by(partition, topic)(kafka_cluster_partition_insyncreplicascount{cluster=\"$cluster\", topic=\"$Topic\", instance=~\"$[[instance]]|$instance\"})"
      }
     ]
    },
    {
     "title": "Under-replicated Partitions",
     "type": "stat",
     "description": "Number of under-replicated partitions",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_partition_underreplicated{cluster=\"$cluster\", topic=\"$Topic\",instance=~\"$[[instance]]|$instance\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions",
     "type": "stat",
     "description": "Number of partitions with 0 replicas",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kafka_cluster_partition_insyncreplicascount{cluster=\"$cluster\", topic=\"$Topic\", instance=~\"$[[instance]]|$instance\"} < 1)"
      }
     ]
    }
   ]
  }
 ]
}