{
 "title": "Kafka consumer offsets",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Kakfa cluster",
    "query": "label_values(kafka_offset_consumer, cluster)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_offset_consumer{cluster=\"$cluster\"}, topic)"
   },
   {
    "name": "group",
    "label": "Consumer group",
    "query": "label_values(kafka_offset_consumer{cluster=\"$cluster\", topic=\"$topic\"}, group)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster wide", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka consumer offset lag for cluster: $cluster",
   "type": "graph",
   "description": "Kafka offset lag for a consumer group",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_offset_newest{cluster=~\"$cluster\"}) by (topic) -  sum(kafka_offset_consumer{cluster=~\"$cluster\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Consumer group: $group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "group" },
  {
   "title": "Kafka consumer offset lag for: $group",
   "type": "graph",
   "description": "Kafka offset lag for a consumer group",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_offset_newest{topic=\"$topic\",cluster=~\"$cluster\"}) by (topic) -  sum(kafka_offset_consumer{topic=\"$topic\", group=~\"$group\", cluster=~\"$cluster\"}) by (topic)",
     "legendFormat": "{{$group}}"
    }
   ]
  },
  {
   "title": "Kafka consumer offset lag by partition",
   "type": "graph",
   "description": "Kafka offset lag for a consumer group by partition",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_offset_newest{topic=\"$topic\",cluster=~\"$cluster\"}) by (partition) -  sum(kafka_offset_consumer{topic=\"$topic\", group=~\"$group\", cluster=~\"$cluster\"}) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Messages added by partition (per min)",
   "type": "graph",
   "description": "Messages added per partition",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_offset_newest{topic=\"$topic\",cluster=~\"$cluster\"}[1m])) by (partition)",
     "legendFormat": "{{partition}}"
    }
   ]
  }
 ]
}